# Generated by Django 5.1.1 on 2024-10-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('client', 'Client')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
